'use client';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { TamaguiProvider, createTamagui } from 'tamagui';
import { config } from '@tamagui/config/v3';
import styled from 'styled-components';

// you usually export this from a tamagui.config.ts file
const tamaguiConfig = createTamagui(config);

// TypeScript types across all Tamagui APIs
type Conf = typeof tamaguiConfig;
declare module 'tamagui' {
  interface TamaguiCustomConfig extends Conf {}
}

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ContainerBody = styled.body`
  width: 100%;
  height: 100%;
`;
const ContainerDiv = styled.div`
  width: 100%;
  height: 100%;
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContainerBody>
        <TamaguiProvider config={tamaguiConfig}>
          <ContainerDiv
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </ContainerDiv>
        </TamaguiProvider>
      </ContainerBody>
    </html>
  );
}
